### ISSUE TITLE
quasar-core-jdk8 : java.lang.NoClassDefFoundError: jsr166e/ConcurrentHashMapV8

### ISSUE THREAD

**Issue by maoxianfly** [puniverse/quasar#95] opened 2015-06-09 11:49 UTC
Exception in thread "main" java.lang.NoClassDefFoundError: jsr166e/ConcurrentHashMapV8
	at co.paralleluniverse.concurrent.util.MapUtil.newConcurrentHashMap(MapUtil.java:20)
	at co.paralleluniverse.fibers.instrument.SuspendableHelper.<clinit>(SuspendableHelper.java:29)
	at co.paralleluniverse.fibers.Fiber.<clinit>(Fiber.java:92)

**Comment by pron** [comment] 2015-06-09 11:50
Duplicate of #95

The problem is with the jdk8 artifact, and is fixed in an upcoming release (very soon). In the meantime use the plain, non-jdk8 artifact (it should work even with Java 8).

**Closed by pron** 2015-06-09 11:50 UTC
