### ISSUE TITLE
Calling ReentrantLock.lock() ends with NPE

### ISSUE THREAD

**Issue by mnowrot** [puniverse/quasar#80] opened 2015-02-23 15:57 UTC
After calling ReentrantLock.lock() the following is thrown:
```
java.lang.NullPointerException
	at co.paralleluniverse.strands.Strand.park(Strand.java:495)
	at co.paralleluniverse.strands.concurrent.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:838)
	at co.paralleluniverse.strands.concurrent.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:872)
	at co.paralleluniverse.strands.concurrent.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1203)
	at co.paralleluniverse.strands.concurrent.ReentrantLock$NonfairSync.lock(ReentrantLock.java:207)
	at co.paralleluniverse.strands.concurrent.ReentrantLock.lock(ReentrantLock.java:285)
	(...)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:42)
	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:30)
	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1012)
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1007)
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:719)
	at co.paralleluniverse.fibers.FiberForkJoinScheduler$FiberForkJoinTask.exec1(FiberForkJoinScheduler.java:248)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.doExec(ParkableForkJoinTask.java:116)
	at co.paralleluniverse.concurrent.forkjoin.ParkableForkJoinTask.exec(ParkableForkJoinTask.java:73)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by circlespainter** [comment] 2015-02-23 15:59
Is instrumentation ok according to `-Dco.paralleluniverse.fibers.verifyInstrumentation=true`? If it is, can you post the relevant code?

**Comment by mnowrot** [comment] 2015-02-23 16:11
Instrumentation seems to be ok, at least running the application with `-Dco.paralleluniverse.fibers.verifyInstrumentation=true` does not print any errors/warnings. What's strange, when running the application with `-Dco.paralleluniverse.fibers.verifyInstrumentation=true` the exeption is not thrown.

The code you requested:
```
        LOCK.lock();
        try {
            tasks.addLast(t);
        } finally {
            LOCK.unlock();
        }
```

**Comment by circlespainter** [comment] 2015-02-23 20:29
So far I'm unable to reproduce it; I basically started from a test project generated through https://github.com/puniverse/quasar-mvn-archetype and replaced the main class source with this:

```java
package testgrp;

import co.paralleluniverse.strands.Strand;
import co.paralleluniverse.strands.concurrent.ReentrantLock;

public class QuasarIncreasingEchoApp {
    static public void doAll() {
        ReentrantLock l = new ReentrantLock();
        System.out.println(Strand.currentStrand().getName() + " - Locking");
        l.lock();
        try {
            System.out.println(Strand.currentStrand().getName() + " - In lock");
        } finally {
            System.out.println(Strand.currentStrand().getName() + " - Unlocking");
            l.unlock();
            System.out.println(Strand.currentStrand().getName() + " - Unlocked");
        }
    }

    public static void main(String[] args) {
        doAll();
    }
}
```

I tried both with and without instrumentation verification. Am I doing something different from you?

**Comment by mnowrot** [comment] 2015-02-24 08:56
Actually, it seems that only one thread is going through your implementation, takes the lock and then releases. Please try an example where multiple threads are waiting on a taken lock.

**Comment by circlespainter** [comment] 2015-02-24 09:34
Ah right, I misunderstood your sample then, I thought you had this exception even in the very basic case of a single thread calling it.

**Comment by circlespainter** [comment] 2015-02-24 09:57
Ok, I tried with this one but I'm still unable to reproduce it no matter what the combination of thread, fiber and instrumentation verification flag I use (running on Mac OS X Yosemite, Java 1.8.0_31-b13, Quasar 0.6.2):

```java
package testgrp;

import co.paralleluniverse.fibers.SuspendExecution;
import co.paralleluniverse.strands.Strand;
import co.paralleluniverse.strands.SuspendableRunnable;
import co.paralleluniverse.strands.concurrent.ReentrantLock;

import java.util.concurrent.ExecutionException;

public class QuasarIncreasingEchoApp {
    public static void main(String[] args) throws InterruptedException, ExecutionException {
        final ReentrantLock l = new ReentrantLock();

        final SuspendableRunnable sr = new SuspendableRunnable() {
            @Override
            public void run() throws SuspendExecution, InterruptedException {
                System.out.println(Strand.currentStrand().getName() + " - Locking");
                l.lock();
                try {
                    System.out.println(Strand.currentStrand().getName() + " - In lock, sleeping");
                    Strand.sleep(1000);
                    System.out.println(Strand.currentStrand().getName() + " - In lock, after sleeping");
                } finally {
                    System.out.println(Strand.currentStrand().getName() + " - Unlocking");
                    l.unlock();
                    System.out.println(Strand.currentStrand().getName() + " - Unlocked");
                }
            }
        };

        final Runnable r = new Runnable() {
            @Override
            public void run() {
                try {
                    sr.run();
                } catch (SuspendExecution | InterruptedException e) {
                    throw new AssertionError(e);
                }
            }
        };

        // final Fiber s1 = new Fiber(sr);
        // final Fiber s2 = new Fiber(sr);
        final Thread s1 = new Thread(r);
        final Thread s2 = new Thread(r);

        s1.start();
        s2.start();

        s1.join();
        s2.join();
    }
}
```

**Comment by mnowrot** [comment] 2015-02-24 10:15
Now this resembles my code. Please a) make more threads compete for the same lock (ca 20-30) b) make sure that Strand.park (see my stack trace above) has been called at least once

**Comment by circlespainter** [comment] 2015-02-24 10:45
Still no exceptions with this:

```java
package testgrp;

import co.paralleluniverse.fibers.Fiber;
import co.paralleluniverse.fibers.SuspendExecution;
import co.paralleluniverse.strands.Strand;
import co.paralleluniverse.strands.SuspendableRunnable;
import co.paralleluniverse.strands.concurrent.ReentrantLock;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.ThreadLocalRandom;

public class QuasarIncreasingEchoApp {
    private static final int CONTENTION = 100;

    public static void main(String[] args) throws InterruptedException, ExecutionException {
        final ReentrantLock l = new ReentrantLock();

        final SuspendableRunnable sr = new SuspendableRunnable() {
            @Override
            public void run() throws SuspendExecution, InterruptedException {
                System.out.println(Strand.currentStrand().getName() + " - Parking");
                Strand.parkNanos(100000000);
                System.out.println(Strand.currentStrand().getName() + " - Locking");
                l.lock();
                try {
                    System.out.println(Strand.currentStrand().getName() + " - In lock, parking");
                    Strand.parkNanos(500000000);
                    System.out.println(Strand.currentStrand().getName() + " - In lock, after parking");
                } finally {
                    System.out.println(Strand.currentStrand().getName() + " - Unlocking");
                    l.unlock();
                    System.out.println(Strand.currentStrand().getName() + " - Unlocked");
                }
            }
        };

        final Runnable r = new Runnable() {
            @Override
            public void run() {
                try {
                    sr.run();
                } catch (SuspendExecution | InterruptedException e) {
                    throw new AssertionError(e);
                }
            }
        };

        final Strand[] strands = new Strand[CONTENTION];
        for(int i = 0 ; i < strands.length ; i++) {
            if (ThreadLocalRandom.current().nextBoolean())
                strands[i] = Strand.of(new Thread(r));
            else
                strands[i] = new Fiber(sr);
        }
        for(int i = 0 ; i < strands.length ; i++)
            strands[i].start();
        for(int i = 0 ; i < strands.length ; i++)
            strands[i].join();
    }
}
```

Which Java & Quasar versions are you using and on which platform? Could post even a very cut-down code sample that triggers systematically the issue?

**Comment by mnowrot** [comment] 2015-02-24 11:06
Ok, here's the code:

```java
package mypackage;

import java.util.concurrent.locks.Lock;
import javax.annotation.Nonnull;

import co.paralleluniverse.strands.concurrent.ReentrantLock;
import javolution.util.FastTable;

public class TasksList {
    /**
     * Lock for providing effective atomicity for reading updating the tsk list
     */
    private final ReentrantLock LOCK = new ReentrantLock();

    /**
     * A lists of tasks to be done on the this thread only.
     */
    private final FastTable<Runnable> tasks = new FastTable<>();

    public void processTasks() {

        LOCK.lock();
        try {
            final int size = tasks.size();
            for (int i = size - 1; i >= 0; --i) {

                @Nonnull
                final Runnable t = tasks.get(i);

                t.run();
            }

            tasks.clear();
        } finally {
            LOCK.unlock();
        }
    }

    /**
     * Tasks can be added by any thread
     */
    public void addTask(@Nonnull Runnable t) {
        // slow path
        LOCK.lock();
        try {
            tasks.addLast(t);
            hasTasks = true;
        } finally {
            LOCK.unlock();
        }
    }
}

```

**Comment by circlespainter** [comment] 2015-02-24 14:30
Thanks, so I included your class (together with javolution 6.0.0 as well as jsr305 3.0.0) and I'm using this now:

```java
public class QuasarIncreasingEchoApp {
    private static final int CONTENTION = 100;

    private static Runnable toRunnable(SuspendableRunnable sr) {
        return new Runnable() {
            @Override
            public void run() {
                try {
                    sr.run();
                } catch (SuspendExecution | InterruptedException e) {
                    throw new AssertionError(e);
                }
            }
        };
    }

    public static void main(String[] args) throws InterruptedException, ExecutionException {
        final TasksList tl = new TasksList();

        final SuspendableRunnable sr = new SuspendableRunnable() {
            @Override
            public void run() throws SuspendExecution, InterruptedException {
                tl.addTask(toRunnable(this));
            }
        };

        final Runnable r = toRunnable(sr);

        final Strand[] strands = new Strand[CONTENTION];
        for(int i = 0 ; i < strands.length ; i++) {
            if (ThreadLocalRandom.current().nextBoolean())
                strands[i] = Strand.of(new Thread(r));
            else
                strands[i] = new Fiber(sr);
        }
        for(int i = 0 ; i < strands.length ; i++)
            strands[i].start();
        for(int i = 0 ; i < strands.length ; i++)
            strands[i].join();
    }
}
```

Still I can't reproduce it with the latest 0.6.3-SNAPSHOT, I tried both the regular and `jdk8` version. Can you try with the latest snapshot? If it still doesn't work, could you share a `main` using your `TaskList` class and triggering the issue?

There was a problem with the `jdk8` version of 0.6.3-SNAPSHOT on Sonatype Snapshots (missing ASM) but the one uploaded few mins ago is fixed.

**Comment by circlespainter** [comment] 2015-02-26 12:52
@mnowrot Have you got the chance of trying with the latest 0.6.3-SNAPSHOT?

**Comment by mnowrot** [comment] 2015-03-02 15:38
Hi @circlespainter - yes, sorry for a delay, I've checked out and built the fresh version today, but unfortunately, nothing changed w.r.t. behavior. The NPE is still being thrown.

**Comment by circlespainter** [comment] 2015-03-02 16:37
Could you share a main using your `TaskList` class and systematically triggering the issue? A whole small project (Maven or Gradle) would be even better.

**Comment by circlespainter** [comment] 2015-03-07 16:41
@mnowrot Would it be possible to have such code? It doesn't need to be the full code, on the contrary the smaller the better. I've tried to reproduce it but I couldn't so far, plus the stack trace is a bit strange: can't see a NPE possible looking at the code, so I believe it must have something to do with instrumentation and it can be hard to figure out without a way to reproduce it.

**Comment by mnowrot** [comment] 2015-03-19 10:35
@circlespainter sorry I wasn't responsive for the previous days, things have been busy on my end. 

I did a few additional test and logging and the following has occurred:
1) There are 3 OS threads and 4 fiber worker threads competing for this lock
2) Not all the calls to lock() end with this exception, however in first 100 calls it is very likely that one will be thrown
3) In your code above, only addTask is called - could you please also call processTasks()? And maybe choose to call these two methods at random from many different threads and fibers?
4) The exception is thrown only when a fiber worker thread is calling the lock(); - so far I didn't observe any crashes caused by other threads calling lock(); - however as I mentioned in 2) there are also successful calls to lock(); made by fiber worker threads

I hope the information above will help you pinpoint the problem. Unfortunately, I can't share any more code, as I don't have any rights to do it. The software I'm developing is proprietary.

**Comment by circlespainter** [comment] 2015-03-22 10:49
Ok, so here's my latest attempt to reproduce it: https://github.com/circlespainter/reproduce-quasar-80.

I could get the exception you mentioned only before declaring `addTask` and `processTask` as `@Suspendable`, which is needed because Parallel Universe's `ReentrantLock` works on all strands (both threads and fibers) and so it can park fibers. It uses the `@Suspendable` annotation rather than declaring throwing `SuspendExecution` only in order to retain compatibility with JDK's `Lock` interface it implements. Does adding `@Suspendable` eliminate the exception for you too?

Also, you're using `Runnable` to represent tasks but if their `run` implementations ever call suspendable (i.e. potentially fiber-parking) ops, then it's better to use `SuspendableRunnable` instead.
Or you could declare your `run` method implementation as `@Suspendable` and include `java.lang.Runnable.run` in `suspendable-supers`, like I did in my prj. just in order to avoid deviating too much from your code, but this is inefficient and doesn't leverage help from checked exceptions.

As to why instrumentation verification sometimes fails to point out the uninstrumented spot, soon I'm going to open an issue about that.

**Comment by circlespainter** [comment] 2015-04-01 14:24
@mnowrot I'd close this one early next week unless you have some feedback (you can always re-open it).

**Comment by mnowrot** [comment] 2015-04-21 10:17
Unfortunately, adding @Suspendable to both methods did not help (the NPEs are still being thrown), although much less often. Test sample was ca. 4.000.000 add/process operations.

**Comment by circlespainter** [comment] 2015-04-22 06:54
@mnowrot How about the tasks, have you tried converting them from `Runnable` to `SuspendableRunnable`?

**Comment by circlespainter** [comment] 2015-06-04 17:24
@mnowrot Have you had a chance to take a look?

**Comment by pron** [comment] 2015-07-01 16:34
@mnowrot Does the issue persist with the latest release (0.7.2)? We've fixed some instrumentation-related edge-cases.

**Comment by pron** [comment] 2015-07-15 14:55
Closing for inactivity. Please reopen if the issue has not been resolved.

**Closed by pron** 2015-07-15 14:55 UTC
